image:
- Visual Studio 2017
#- Ubuntu

stack: python 3.6

environment:
  PY_DIR: C:\Python36

platform: x86

build: off

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

install:
  - sh: wget -q -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb && dpkg -i /tmp/libpng12.deb && rm /tmp/libpng12.deb
  - sh: sudo apt-get install -y libpython3.6-dev libftdi1 libftdi1-dev
  - sh: pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 wxPython
  - cmd: pip install wxPython
  - pip install libusb1
  - pip install pylibftdi
  - pip install pyinstaller

build_script:
  - python -m PyInstaller --onefile --clean HondaECU.py
  - python -m PyInstaller --onefile --clean gui.py

artifacts:
  - path: dist\*

deploy:

  provider: GitHub
  description: 'Honda ECU K-line commandline tool'
  auth_token:
    secure: VDADKxNk9UEQ11Ycj0bjwqi5yzJKuKOZ+qAWu5vfPqSQTeJDiCoqWSuCLYK1o2pC
  artifact: /.*\.exe/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
