image:
- Visual Studio 2017
#- Ubuntu

stack: python 3.6

environment:
  PY_DIR: C:\Python36

platform: x86

build: off

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

install:
  - sh: sudo apt-get install -y libpython3.6-dev
  - pip install pylibftdi
  - pip install pyinstaller

build_script:
  - python -m PyInstaller --onefile --clean flash.py

artifacts:
  - path: dist\*
  
deploy:
  release: HondaECU-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: c6843d5a7453c9d4c55854e585869af2cdfdd62b
  artifact: /.*\.exe/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
