image:
- Visual Studio 2017
- Ubuntu

stack: python 3

environment:
  PY_DIR: C:\Python36

platform: x86

build: off

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

install:
  - cmd: pip install pylibftdi"
  - cmd: pip install pyinstaller"

build_script:
  - cmd: python -m PyInstaller --onefile --clean flash.py"

artifacts:
  - path: dist\*
