image:
- Visual Studio 2017
- Ubuntu

stack: python 3.6

environment:
  PY_DIR: C:\Python36

platform: x86

build: off

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

install:
  - sh: sudo apt-get install -y python3-dev
  - pip install pylibftdi
  - pip install pyinstaller

build_script:
  - python -m PyInstaller --onefile --clean flash.py

artifacts:
  - path: dist\*
