image:
- Visual Studio 2017

environment:
  matrix:
    - MSYS2_ARCH: i686
      MSYSTEM: MINGW32

build: off

init:
- cmd: set PATH=C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;%PATH%

install:
  - cmd: bash -lc "pacman --noconfirm --sync --refresh --refresh pacman"
  - cmd: bash -lc "pacman --noconfirm --sync --refresh --refresh --sysupgrade --sysupgrade"
  - cmd: bash -xlc "pacman --noconfirm -S --needed base-devel"
  - cmd: bash -xlc "pacman --noconfirm -S --needed mingw-w64-libusb"
  - cmd: bash -xlc "pacman --noconfirm -S --needed mingw-w64-wxPython"
  - cmd: bash -xlc "pacman --noconfirm -S --needed mingw-w64-%MSYS2_ARCH%-python3"
  - cmd: bash -xlc "pip install libusb1"
  - cmd: bash -xlc "pip install pylibftdi"
  - cmd: bash -xlc "pip install pyinstaller"

build_script:
  - cmd: bash -xlc "python3 -m PyInstaller --onefile --clean HondaECU.py"
  - cmd: bash -xlc "python3 -m PyInstaller --onefile --clean gui.py"

artifacts:
  - path: dist\*

deploy:

  provider: GitHub
  description: 'Honda ECU K-line commandline tool'
  auth_token:
    secure: VDADKxNk9UEQ11Ycj0bjwqi5yzJKuKOZ+qAWu5vfPqSQTeJDiCoqWSuCLYK1o2pC
  artifact: /.*\.exe/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
