image:
  - Visual Studio 2017
  #- Ubuntu

stack: python 3.6

environment:
  PY_DIR: C:\Python36
  matrix:
    - platform: x86
      LIBUSB: "MS32/dll/libusb-1.0.dll"
      LIBFTDI: "libftdi1-1.4git_devkit_x86_x64_14June2018/bin32/libftdi1.dll"
      SUFFIX: "x86"
    - platform: x64
      LIBUSB: "MS64/dll/libusb-1.0.dll"
      LIBFTDI: "libftdi1-1.4git_devkit_x86_x64_14June2018/bin64/libftdi1.dll"
      SUFFIX: "x64"

build: off

init:
  - cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

install:
  - sh: wget -q -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb && dpkg -i /tmp/libpng12.deb && rm /tmp/libpng12.deb
  - sh: sudo apt-get install -y libpython3.6-dev libftdi1 libftdi1-dev
  - sh: pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 wxPython
  - ps: Start-FileDownload 'https://github.com/libusb/libusb/releases/download/v1.0.22/libusb-1.0.22.7z'
  - ps: Invoke-WebRequest -Uri 'https://sourceforge.net/projects/picusb/files/libftdi1-1.4git_devkit_x86_x64_14June2018.zip/download?use_mirror=newcontinuum&r=&use_mirror=newcontinuum' -OutFile libftdi1-1.4git_devkit_x86_x64_14June2018.zip -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome
  - cmd: 7z x libusb-1.0.22.7z
  - cmd: 7z x libftdi1-1.4git_devkit_x86_x64_14June2018.zip
  - cmd: pip install wxPython
  - pip install libusb1
  - pip install pylibftdi
  - pip install pyinstaller

build_script:
  - cmd: python -m PyInstaller --onefile --clean ecu.py --name HondaECU_old
  - cmd: python -m PyInstaller --onefile --clean --add-binary honda.ico;. --add-binary waitoff.gif;. --add-binary waiton.gif;. --add-binary %LIBUSB%;. --add-binary %LIBFTDI%;. gui.py --name HondaECU_%SUFFIX% --icon=honda.ico

artifacts:
  - path: dist\*

deploy:

  provider: GitHub
  description: 'Honda ECU K-line commandline tool'
  auth_token:
    secure: VDADKxNk9UEQ11Ycj0bjwqi5yzJKuKOZ+qAWu5vfPqSQTeJDiCoqWSuCLYK1o2pC
  artifact: /.*\.exe/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
