image:
- Visual Studio 2017
#- Ubuntu

stack: python 3.6

environment:
  PY_DIR: C:\Python36

platform: x86

build: off

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

install:
  - sh: sudo apt-get install -y libpython3.6-dev libftdi1 libftdi1-dev
  - pip install pylibftdi
  - pip install pyinstaller

build_script:
  - python -m PyInstaller --onefile --clean HondaECU.py

artifacts:
  - path: dist\*

deploy:

  provider: GitHub
  description: 'Honda ECU K-line commandline tool'
  auth_token:
    secure: VDADKxNk9UEQ11Ycj0bjwqi5yzJKuKOZ+qAWu5vfPqSQTeJDiCoqWSuCLYK1o2pC
  artifact: /.*\.exe/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
